### ISSUE TITLE
Passing parameter still asks for inputs

### ISSUE THREAD

**Issue by Power-Maverick** [DynamicsNinja/generator-pcf#2]
When using parameters can you avoid any user inputs in the console? Right now even if package is selected in the parameter user input is required in the console.

![image](https://user-images.githubusercontent.com/36135520/83364138-ec088c00-a36c-11ea-80c1-1661f66cd2f6.png)

Thanks.

**Comment by DynamicsNinja** [comment]
It's a bug only when you pass 0 as the pkg value. Forgot that 0 is considered as falsy value in JS. Will fix it in the next release 😉
